# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 13:27
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bid', verbose_name='Bid'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='currency',
            field=models.CharField(choices=[('rur', '\u20bd'), ('usd', '$'), ('eur', '€')], default='rur', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='url',
            field=models.URLField(max_length=2048, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='product',
            field=models.TextField(max_length=500, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('O', 'Opened'), ('R', 'Running'), ('C', 'Closed'), ('S', 'Succefully closed'), ('P', 'Protest'), ('A', 'Protest analysis'), ('E', 'Protestly closed')], default='O', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=30, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone number'),
        ),
    ]
