# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161203_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='lifetime',
            field=models.PositiveIntegerField(default='5', verbose_name='Lifetime, min'),
        ),
    ]
