# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20161217_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='status',
            new_name='_status',
        ),
    ]
