# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20161221_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='timeleft',
            field=models.PositiveIntegerField(default='5', verbose_name='Timeleft, sec'),
        ),
    ]
