# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-23 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bid_timeleft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='timeleft',
            new_name='_timeleft',
        ),
    ]
